[workspace]
resolver = "2"
members = [
    "lifec",
    "lifec_poem",
]

[patch.crates-io]
specs = { git = 'https://github.com/juliusl/specs.git', branch = "fix/ahash"}
shred = { git = 'https://github.com/juliusl/shred.git', branch = "fix/ahash"}