[package]
name = "lifec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
logos = "0.12.0"

# Add's support for built-in editors
atlier = { path = "../atlier" } #{ git = "https://github.com/juliusl/atlier.git"   }
imnodes = { git = "https://github.com/benmkw/imnodes-rs.git" }
knot = { git = "https://github.com/juliusl/knot.git"  }
imgui = { version = "0.8.2" }
specs = "0.17.0"
rand = "0.8.5"
