[package]
name = "lifec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"

# For Event Editor
atlier = { path = "../atlier/" }
imnodes = { path = "../atlier/imnodes-rs" }
imgui = { version = "0.8.2" }
knot = { path = "../knot" }