[package]
name = "osprocess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atlier = { path = "../../../atlier" }
chrono = "0.4.19"
imgui = "0.8.2"
lifec = { path = "../.." }
specs = "0.17.0"
