[package]
name = "carddeck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgui = "0.8.2"
lifec = { path = "../.." }
logos = "0.12.0"
rand = "0.8.5"
specs = "0.17.0"
