[package]
name = "event_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atlier = { path = "../../../atlier" }
carddeck = { path = "../carddeck" }
imgui = "0.8.2"
imnodes = { path = "../../../atlier/imnodes-rs" }
lazy_static = "1.4.0"
lifec = { path = "../.." }
thread-safe = "0.1.2"
